### ISSUE TITLE
eID and Apache Tomcat

### ISSUE THREAD

**Issue by Tiemen92** [JensTimmerman/beidtest#2]
Hi, I was trying to use your code but it uses Glassfish as server. Is it possible to use this with Tomcat and how?

Thanks

**Comment by JensTimmerman** [comment]
I'm sure it is possible,

As in the readme, I got this code from http://www.youtube.com/watch?v=x1dARGV_zEQ&html5=1
Netbeans asks you what server you want to use (at 3:50) when you first deploy the webapp. I selected glassfish and this created the src/main/webapp/WEB-INF/glassfish-web.xml file.
Remove this file, and deploy the webapp, netbeans should ask you again, select tomcat, and follow the steps.

**Comment by JensTimmerman** [comment]
Alternatively, leave the file in place, but in netbeans
go to the services tab, richtclick servers, add server, select tomcat and  the path where you installed tomcat.

The above, and this should work, but was untested by me.

**Comment by Tiemen92** [comment]
Thanks, I've tried this but I'm still getting the "ERROR: no session cookie detected!" message.
Do you have any idea how to fix this using Tomcat?

**Comment by JensTimmerman** [comment]
I'm sorry, but I don't
